"""Skill: Package management (search & write install guides).

Auto-discovered via @tool() decorator — no manual wiring needed.
"""

import datetime
import os
import re
import subprocess

from .._registry import tool


def _search_packages(query: str) -> str:
    """Search pacman and AUR (via yay) for a package, returning top 5 from each."""
    results_parts = []
    pacman = subprocess.run(
        ["pacman", "-Ss", "--color", "never", query],
        capture_output=True,
        text=True,
        timeout=30,
    )
    if pacman.returncode == 0 and pacman.stdout.strip():
        lines = pacman.stdout.strip().split("\n")
        official = [l for l in lines if not l.startswith(" ")]
        if official:
            results_parts.append("Official repositories:\n" + "\n".join(official[:5]))

    yay = subprocess.run(
        ["yay", "-Ss", "--color", "never", query],
        capture_output=True,
        text=True,
        timeout=60,
        env=dict(os.environ),
    )
    if yay.returncode == 0 and yay.stdout.strip():
        lines = yay.stdout.strip().split("\n")
        aur = [l for l in lines if "aur/" in l.lower()][:5]
        if aur:
            results_parts.append("AUR:\n" + "\n".join(aur))

    if not results_parts:
        return f"No packages found for '{query}'."
    return "\n\n".join(results_parts)


def _install_package(package_name: str) -> str:
    """Generate an install guide MD file (does NOT actually install anything)."""
    from src.config import install_guides_dir

    sanitized = re.sub(r'[^a-zA-Z0-9._-]', '_', package_name)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{sanitized}-{timestamp}.md"
    outdir = install_guides_dir()
    path = outdir / filename

    content = (
        f"# Install Guide: {package_name}\n\n"
        f"## pacman\n"
        f"```bash\n"
        f"sudo pacman -S {package_name}\n"
        f"```\n\n"
        f"## AUR (yay)\n"
        f"```bash\n"
        f"yay -S {package_name}\n"
        f"```\n\n"
        f"*Generated by GnomePilot — always verify packages before installing.*\n"
    )
    path.write_text(content)
    return str(path)


@tool()
def tool_search_packages(query: str) -> str:
    """Search for available software packages in pacman repositories and the AUR.

    Queries both official Arch repositories and the Arch User Repository (AUR)
    via yay. Returns top results from each.

    Args:
        query: Search term for the package (e.g. "web browser", "htop").
    """
    return _search_packages(query)


@tool()
def tool_install_package(package_name: str) -> str:
    """Generate an install guide with exact commands for a software package.

    Does NOT install anything. Creates an MD file with pacman/yay commands
    that the user can run manually. Use after confirming the package name
    with tool_search_packages.

    Args:
        package_name: Name of the package to write instructions for.
    """
    return _install_package(package_name)
